### ISSUE TITLE
In Notifications username truncated

### ISSUE THREAD

**Issue by hirowatch** [CrazyHackGUT/XF-Telegram#1]
![2018-08-03_15-52-53](https://user-images.githubusercontent.com/40771558/43643882-5a7407b4-9735-11e8-8f9d-ad7bdffc83b1.png)
![2018-08-03_15-36-31](https://user-images.githubusercontent.com/40771558/43643890-611ce50e-9735-11e8-8509-82d7673ac08a.png)

**Comment by CrazyHackGUT** [comment]
Looks like a conflict between Telegram addon and Verifier.
![default](https://user-images.githubusercontent.com/12576822/43647490-d26c5a56-9748-11e8-8a4d-ba8b73614841.png)

**Comment by CrazyHackGUT** [comment]
Well, we plan fix this shit.
So let him opened.

**Comment by CrazyHackGUT** [comment]
This should be fixed after separating addons because i implemented new HTML Purifier. Test, please, and if bug still exists - create a Issue in [Notifications repo](https://github.com/XF-Telegram/Notifications).
